#!/usr/bin/env bash
# regenerates requirements.lock.txt for the isolated AGT fixture.
#
# resolves agent-governance-toolkit-core==4.1.0 plus transitives with pip,
# verifies the core wheel sha256 against pins.json, and emits a
# --require-hashes lock. note: compiled wheels (aiohttp, cryptography, ...)
# are platform-specific, so regenerate the lock on the platform where the
# fixture will run.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON="${PYTHON:-python3.13}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
shopt -s nullglob

"$PYTHON" -m venv "${TMP}/venv"
"${TMP}/venv/bin/pip" download --quiet agent-governance-toolkit-core==4.1.0 -d "${TMP}/wheels"

WANT_SHA="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["wheel"]["sha256"])' "${HERE}/pins.json")"
core_wheels=("${TMP}"/wheels/agent_governance_toolkit_core-4.1.0-*.whl)
if [ "${#core_wheels[@]}" -ne 1 ]; then
  echo "error: expected exactly one agent-governance-toolkit-core 4.1.0 wheel, found ${#core_wheels[@]}" >&2
  exit 1
fi
GOT_SHA="$(shasum -a 256 "${core_wheels[0]}" | awk '{print $1}')"
if [ "$GOT_SHA" != "$WANT_SHA" ]; then
  echo "error: resolved core wheel sha256 mismatch (got ${GOT_SHA}, want ${WANT_SHA})" >&2
  exit 1
fi

"$PYTHON" - "$TMP/wheels" "${HERE}/requirements.lock.txt" <<'EOF'
import hashlib, pathlib, re, sys

wheels_dir, out_path = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
lines = [
    "# hash-locked dependency set for the isolated AGT fixture (agent-governance evidence spike)",
    "# generated by adapters/agt/lock.sh on macOS arm64 / CPython 3.13 — regenerate on other platforms",
    "# core pin: agent-governance-toolkit-core==4.1.0 (wheel sha256 verified against the SPEC lock before install)",
]
entries = {}
for w in sorted(wheels_dir.iterdir()):
    m = re.match(r"^([A-Za-z0-9_.]+)-([0-9][^-]*)-", w.name)
    if not m:
        raise SystemExit(f"unparsed artifact name: {w.name}")
    name = m.group(1).replace("_", "-").lower()
    digest = hashlib.sha256(w.read_bytes()).hexdigest()
    entries.setdefault((name, m.group(2)), []).append(digest)
for (name, version), digests in sorted(entries.items()):
    hash_str = " \\\n    ".join(f"--hash=sha256:{d}" for d in digests)
    lines.append(f"{name}=={version} \\\n    {hash_str}")
out_path.write_text("\n".join(lines) + "\n")
print(f"wrote {out_path} ({len(entries)} locked packages)")
EOF
