// Command checkpoint verifies the immutable pre-extraction SHA-256 manifest
// for the agent-governance companion.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/liatrio/autogov/agent-governance/internal/demokit"
)

const (
	manifestFilename = "checkpoint.sha256.json"
	baselineCommit   = "c11a1b0fbe02de266ba11963abedd0d07f427be9"
)

var caseNames = []string{
	"allowed-action",
	"denied-action",
	"adapter-bypass",
	"no-policy-loaded",
	"unknown-outcome",
}

type manifest struct {
	SchemaVersion  string  `json:"schemaVersion"`
	BaselineCommit string  `json:"baselineCommit"`
	Entries        []entry `json:"entries"`
}

type entry struct {
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	SHA256 string `json:"sha256"`
}

func main() {
	if err := run(os.Args[1:], os.Stderr); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return
		}
		fatal(err)
	}
}

func run(args []string, stderr io.Writer) error {
	flags := flag.NewFlagSet("checkpoint", flag.ContinueOnError)
	flags.SetOutput(stderr)
	root := flags.String("root", "", "path to the agent-governance directory")
	writeManifest := flags.Bool("write", false, "unsupported: the committed checkpoint is immutable")
	verifyManifest := flags.Bool("verify", false, "compare generated bytes with the committed manifest")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected positional arguments: %v", flags.Args())
	}
	if *root == "" {
		return errors.New("-root is required")
	}
	if *writeManifest {
		return errors.New("-write is disabled: the committed checkpoint is immutable")
	}
	if !*verifyManifest {
		return errors.New("-verify is required: the post-checkpoint command is verify-only")
	}

	data, err := buildManifest(*root)
	if err != nil {
		return err
	}
	path := filepath.Join(*root, manifestFilename)
	want, err := os.ReadFile(path)
	if err == nil && !bytes.Equal(data, want) {
		err = fmt.Errorf("%s does not match generated checkpoint", path)
	}
	return err
}

func buildManifest(root string) ([]byte, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("resolve root: %w", err)
	}
	frozen, err := frozenInputPaths(absRoot)
	if err != nil {
		return nil, err
	}

	entries := make([]entry, 0, 64)
	for _, producer := range []string{"agt", "non-agt"} {
		for _, caseName := range caseNames {
			evidencePath := filepath.Join(absRoot, "fixtures", "evidence", producer, caseName+".json")
			built, err := demokit.BuildCase(evidencePath)
			if err != nil {
				return nil, fmt.Errorf("build %s/%s: %w", producer, caseName, err)
			}
			name := producer + "/" + caseName + ".json"
			entries = append(entries,
				entry{Kind: "predicate-body", Name: name, SHA256: hashBytes(built.PredicateBody)},
				entry{Kind: "test-result-statement", Name: name, SHA256: hashBytes(built.TestResultStatement)},
			)
		}
	}

	policyDigest, err := calculatePolicyDirectoryDigest(filepath.Join(absRoot, "policy"))
	if err != nil {
		return nil, err
	}
	entries = append(entries, entry{
		Kind:   "policy-bundle",
		Name:   "policy",
		SHA256: policyDigest,
	})

	for _, rel := range frozen {
		data, err := os.ReadFile(filepath.Join(absRoot, filepath.FromSlash(rel)))
		if err != nil {
			return nil, fmt.Errorf("read frozen input %s: %w", rel, err)
		}
		entries = append(entries, entry{Kind: "frozen-input", Name: rel, SHA256: hashBytes(data)})
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Kind != entries[j].Kind {
			return entries[i].Kind < entries[j].Kind
		}
		return entries[i].Name < entries[j].Name
	})

	output, err := json.MarshalIndent(manifest{
		SchemaVersion:  "1",
		BaselineCommit: baselineCommit,
		Entries:        entries,
	}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal manifest: %w", err)
	}
	return append(output, '\n'), nil
}

func frozenInputPaths(root string) ([]string, error) {
	for _, rel := range frozenInputs {
		info, err := os.Lstat(filepath.Join(root, filepath.FromSlash(rel)))
		if err != nil {
			return nil, fmt.Errorf("resolve frozen input %s: %w", rel, err)
		}
		if !info.Mode().IsRegular() {
			return nil, fmt.Errorf("frozen input %s must be a regular non-symlink file", rel)
		}
	}
	return append([]string(nil), frozenInputs...), nil
}

// frozenInputs is explicit so ignored caches or unrelated untracked files can
// never change the committed extraction checkpoint.
var frozenInputs = []string{
	"adapters/agt/lock.sh",
	"adapters/agt/pins.json",
	"adapters/agt/producer.py",
	"adapters/agt/requirements.lock.txt",
	"adapters/agt/runtime_policy.yaml",
	"adapters/agt/setup.sh",
	"adapters/agt/verify_pins.sh",
	"adapters/non-agt/producer.py",
	"adapters/non-agt/runtime_policy.json",
	"adapters/non-agt/toy_runtime.py",
	"fixtures/agent/agent-image.txt",
	"fixtures/evidence/agt/adapter-bypass.json",
	"fixtures/evidence/agt/allowed-action.json",
	"fixtures/evidence/agt/denied-action.json",
	"fixtures/evidence/agt/no-policy-loaded.json",
	"fixtures/evidence/agt/records/agt-adapter-bypass-001-outcome.json",
	"fixtures/evidence/agt/records/agt-allowed-action-001-decision.json",
	"fixtures/evidence/agt/records/agt-allowed-action-001-outcome.json",
	"fixtures/evidence/agt/records/agt-denied-action-001-decision.json",
	"fixtures/evidence/agt/records/agt-denied-action-001-outcome.json",
	"fixtures/evidence/agt/records/agt-no-policy-loaded-001-decision.json",
	"fixtures/evidence/agt/records/agt-no-policy-loaded-001-outcome.json",
	"fixtures/evidence/agt/records/agt-unknown-outcome-001-decision.json",
	"fixtures/evidence/agt/records/audit-config.json",
	"fixtures/evidence/agt/records/audit-sink.json",
	"fixtures/evidence/agt/records/identity.json",
	"fixtures/evidence/agt/records/no-policy.json",
	"fixtures/evidence/agt/unknown-outcome.json",
	"fixtures/evidence/non-agt/adapter-bypass.json",
	"fixtures/evidence/non-agt/allowed-action.json",
	"fixtures/evidence/non-agt/denied-action.json",
	"fixtures/evidence/non-agt/no-policy-loaded.json",
	"fixtures/evidence/non-agt/records/audit-config.json",
	"fixtures/evidence/non-agt/records/audit-sink.json",
	"fixtures/evidence/non-agt/records/identity.json",
	"fixtures/evidence/non-agt/records/no-policy.json",
	"fixtures/evidence/non-agt/records/non-agt-adapter-bypass-001-outcome.json",
	"fixtures/evidence/non-agt/records/non-agt-allowed-action-001-decision.json",
	"fixtures/evidence/non-agt/records/non-agt-allowed-action-001-outcome.json",
	"fixtures/evidence/non-agt/records/non-agt-denied-action-001-decision.json",
	"fixtures/evidence/non-agt/records/non-agt-denied-action-001-outcome.json",
	"fixtures/evidence/non-agt/records/non-agt-no-policy-loaded-001-decision.json",
	"fixtures/evidence/non-agt/records/non-agt-no-policy-loaded-001-outcome.json",
	"fixtures/evidence/non-agt/records/non-agt-unknown-outcome-001-decision.json",
	"fixtures/evidence/non-agt/unknown-outcome.json",
	"fixtures/write_marker.py",
	"policy/agent_governance.rego",
}

// calculatePolicyDirectoryDigest intentionally mirrors AutoGov's public policy
// digest contract: lexically walk the directory, hashing each selected relative
// path followed immediately by its file bytes.
func calculatePolicyDirectoryDigest(dir string) (string, error) {
	h := sha256.New()
	err := filepath.Walk(dir, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if info.IsDir() {
			return nil
		}
		if ext := filepath.Ext(path); ext != ".rego" && ext != ".json" && ext != ".yaml" {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		if _, err := io.WriteString(h, filepath.ToSlash(rel)); err != nil {
			return err
		}
		file, err := os.Open(path)
		if err != nil {
			return err
		}
		_, copyErr := io.Copy(h, file)
		closeErr := file.Close()
		return errors.Join(copyErr, closeErr)
	})
	if err != nil {
		return "", fmt.Errorf("calculate policy bundle digest: %w", err)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func hashBytes(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "checkpoint:", strings.TrimSpace(err.Error()))
	os.Exit(1)
}
